FROM registry.saas.hand-china.com/tools/mysql:5.6
COPY ./sakila-schema.sql sakila-schema.sql
COPY ./sakila-data.sql sakila-data.sql
RUN cat sakila-schema.sql > /docker-entrypoint-initdb.d/dump.sql
RUN cat sakila-data.sql > /docker-entrypoint-initdb.d/dump.sql